# Molecule managed

---
all:
  hosts:
    centos7: &id001
      ansible_connection: docker
    ubuntu1604: &id002
      ansible_connection: docker
ungrouped:
  hosts:
    centos7: *id001
    ubuntu1604: *id002
  vars: {}
