---
# tasks file for ansible-elastic-filebeat
- include_tasks: "{{ ansible_os_family  }}.yml"

- name: Install Filebeat
  package:
    name: filebeat
    state: present
  notify: restart_filebeat
  become: yes

- name: Copy Filebeat configuration.
  template:
    src: filebeat.yml.j2
    dest: "/etc/filebeat/filebeat.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart_filebeat
  become: yes

- name: Establishing modules
  template:
    src: modules/{{ item }}.yml.j2
    dest: "/etc/filebeat/modules.d/{{ item }}.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart_filebeat
  become: yes
  with_items: "{{ filebeat_modules }}"
